# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
#
# Invenio-RDM-Records is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.


notifications:
  email: false

sudo: false

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  allow_failures:
    - python: 3.8

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - ./run-tests.sh

after_success:
  - coveralls

# TODO: Fill me for deployment
# deploy:
#   provider: pypi
#   user: lnielsen
#   password:
#     secure:
#   distributions: "sdist bdist_wheel"
#   skip_existing: true
#   on:
#     tags: true
